# Módulo 07, Tarefa 01

Vamos começar a mexer na nossa base de projeto? Já fizemos um exercício de montar a variável resposta, já pudemos perceber que essa atividade pode não ser trivial. Vamos agora trabalhar a base para que fique propícia ao *scikitlearn* para trabalharmos.

Lembrando, a base se chama demo01.csv, e originalmente está publicada [aqui](https://www.kaggle.com/rikdifos/credit-card-approval-prediction).

#### 1) Carregue a base e avalie:

- As variáveis
- Tipos de dados de cada variável
- Quantidade de missings
- Distribuição da variável resposta (mau)

In [5]:
import pandas as pd

df = pd.read_csv('demo01.csv')
df.head()

,sexo,posse_de_veiculo,posse_de_imovel,qtd_filhos,tipo_renda,educacao,estado_civil,tipo_residencia,idade,tempo_emprego,possui_celular,possui_fone_comercial,possui_fone,possui_email,qt_pessoas_residencia,mau
0,M,Y,Y,0,Working,Secondary / secondary special,Married,House / apartment,58.832877,3.106849,1,0,0,0,2.0,False
1,F,N,Y,0,Commercial associate,Secondary / secondary special,Single / not married,House / apartment,52.356164,8.358904,1,0,1,1,1.0,False
2,F,N,Y,0,Commercial associate,Secondary / secondary special,Single / not married,House / apartment,52.356164,8.358904,1,0,1,1,1.0,False
3,M,Y,Y,0,Working,Higher education,Married,House / apartment,46.224658,2.106849,1,1,1,1,2.0,False
4,F,Y,N,0,Working,Incomplete higher,Married,House / apartment,29.230137,3.021918,1,0,0,0,2.0,False

In [4]:
df.info() # Informações sobre as variáveis e tipos de dados

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16650 entries, 0 to 16649
Data columns (total 16 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   sexo                   16650 non-null  object
 1   posse_de_veiculo       16650 non-null  object
 2   posse_de_imovel        16650 non-null  object
 3   qtd_filhos             16650 non-null  int64
 4   tipo_renda             16650 non-null  object
 5   educacao               16650 non-null  object
 6   estado_civil           16650 non-null  object
 7   tipo_residencia        16650 non-null  object
 8   idade                  16650 non-null  float64
 9   tempo_emprego          16650 non-null  float64
 10  possui_celular         16650 non-null  int64
 11  possui_fone_comercial  16650 non-null  int64
 12  possui_fone            16650 non-null  int64
 13  possui_email           16650 non-null  int64
 14  qt_pessoas_residencia  16650 non-null  float64
 15  mau                    16650 non-null  bool
dtypes: bool(1), float64(3), int64(5), object(7)
memory usage: 1.9+ MB

In [7]:
df.isnull().sum() # Verifique a quantidade de valores ausentes (missings) em cada coluna

sexo                     0
posse_de_veiculo         0
posse_de_imovel          0
qtd_filhos               0
tipo_renda               0
educacao                 0
estado_civil             0
tipo_residencia          0
idade                    0
tempo_emprego            0
possui_celular           0
possui_fone_comercial    0
possui_fone              0
possui_email             0
qt_pessoas_residencia    0
mau                      0
dtype: int64

In [8]:
df['mau'].describe() # Estatísticas descritivas da variável resposta 'mau'

count     16650
unique        2
top       False
freq      16260
Name: mau, dtype: object

In [9]:
df['mau'].value_counts() # Contagem dos valores únicos na variável resposta 'mau'

mau
False    16260
True       390
Name: count, dtype: int64

#### 2) Vamos montar um metadados

1. Crie um dataframe com os nomes de cada variável e o tipo de dados de cada variável.
2. Adicione uma coluna nesse *dataframe* chamada "qtd_categorias" e coloque nela o número de categorias correspondente de cada variável. 
    Dica: 
        1. inicie uma lista vazia
        2. faça um for ao longo dos nomes das variáveis, 
        3. conte o número de categorias dessa variável 
        4. acumule essa informação de 3. na lista que você criou em 1. 
        5. No final, essa lista pode ser atribuída à nossa variável.
3. Crie variáveis dummy para as variáveis necessárias (i.e. aquelas que são qualitativas e não estão armazenadas como {0, 1} ou {True, False}.

In [12]:
# Criar um dataframe com os nomes e tipos de dados
metadata = pd.DataFrame({'Variável': df.columns, 'Tipo de Dados': df.dtypes})

# Exibir o dataframe de metadados
metadata.head()

                          Variável Tipo de Dados
sexo                          sexo        object
posse_de_veiculo  posse_de_veiculo        object
posse_de_imovel    posse_de_imovel        object
qtd_filhos              qtd_filhos         int64
tipo_renda              tipo_renda        object

In [14]:
# Coluna df chamada "qtd_categorias" e coloque nela o número de categorias correspondente de cada variável. 

# Iniciar uma lista vazia para armazenar o número de categorias de cada variável
qtd_categorias = []

# Iterar sobre as variáveis
for variavel in df.columns:
    # Verificar se a variável é categórica
    if df[variavel].dtype == 'object':
        qtd_categorias.append(len(df[variavel].unique()))
    else:
        qtd_categorias.append(None)  # Para variáveis não categóricas, colocamos None

# Adicionar a lista de contagem de categorias ao dataframe de metadados
metadata['qtd_categorias'] = qtd_categorias

# Exibir o dataframe de metadados atualizado
metadata.head()

                          Variável Tipo de Dados  qtd_categorias
sexo                          sexo        object             2.0
posse_de_veiculo  posse_de_veiculo        object             2.0
posse_de_imovel    posse_de_imovel        object             2.0
qtd_filhos              qtd_filhos         int64             NaN
tipo_renda              tipo_renda        object             5.0

#### 3) Crie variáveis dummy para as variáveis necessárias (i.e. aquelas que são qualitativas e não estão armazenadas como {0, 1} ou {True, False}. Crie um *dataframe* apenas com as variáveis apropriadas para entrada no scikitlearn - elimine as variáveis tipo *str*, mantendo apenas suas versões *dummy*.

In [16]:
# Identificar variáveis categóricas
variaveis_categoricas = metadata[metadata['Tipo de Dados'] == 'object']['Variável'].tolist()

# Criar variáveis dummy usando o pandas
df_dummies = pd.get_dummies(df, columns=variaveis_categoricas, drop_first=True)

# Remover as versões originais do tipo string
df_dummies = df_dummies.select_dtypes(exclude=['object'])

# Exibir as primeiras linhas do DataFrame atualizado
df_dummies.head()

,qtd_filhos,idade,tempo_emprego,possui_celular,possui_fone_comercial,possui_fone,possui_email,qt_pessoas_residencia,mau,sexo_M,...,educacao_Secondary / secondary special,estado_civil_Married,estado_civil_Separated,estado_civil_Single / not married,estado_civil_Widow,tipo_residencia_House / apartment,tipo_residencia_Municipal apartment,tipo_residencia_Office apartment,tipo_residencia_Rented apartment,tipo_residencia_With parents
0,0,58.832877,3.106849,1,0,0,0,2.0,False,True,...,True,True,False,False,False,True,False,False,False,False
1,0,52.356164,8.358904,1,0,1,1,1.0,False,False,...,True,False,False,True,False,True,False,False,False,False
2,0,52.356164,8.358904,1,0,1,1,1.0,False,False,...,True,False,False,True,False,True,False,False,False,False
3,0,46.224658,2.106849,1,1,1,1,2.0,False,True,...,False,True,False,False,False,True,False,False,False,False
4,0,29.230137,3.021918,1,0,0,0,2.0,False,False,...,False,True,False,False,False,True,False,False,False,False

#### 4) Qual variável é mais poderosa?

Considere as variáveis ```possui_email``` e ```posse_de_veiculo```. Faça uma tabela cruzada entre elas e responda qual delas te parece mais poderosa para prever a probabilidade de ```mau = 1```?

In [20]:
# Criar uma tabela cruzada
tabela_cruzada = pd.crosstab(index=df['possui_email'], columns=df['posse_de_veiculo'], values=df['mau'], aggfunc='mean', margins=True, margins_name='Total')

# Exibir a tabela cruzada
tabela_cruzada.head()

posse_de_veiculo         N         Y     Total
possui_email
0                 0.024944  0.021788  0.023731
1                 0.016726  0.024883  0.020270
Total             0.024268  0.022095  0.023423

A variável 'posse_de_veiculo' me parece mais eficiente que 'possui_email' pelos seguintes motios:

* Para clientes que não possuem e-mail (possui_email = 0), a média de mau é mais alta quando posse_de_veiculo = N (sem veículo) em comparação com posse_de_veiculo = Y (com veículo).
    
* Para clientes que possuem e-mail (possui_email = 1), a média de mau é também mais alta quando em posse_de_veiculo = Y em comparação com posse_de_veiculo = N.

#### 5) Salve a base, pois ela será utilizada no final deste módulo.

In [21]:
# Substitua 'caminho/do/arquivo/demo01_transformado.csv' pelo caminho e nome de arquivo desejados
arq = '/Users/Administrador/Meu Drive/Estudo/CursoEBAC/2_Materiais/demo01_transformado.csv'

# Salvar o DataFrame transformado como um novo arquivo CSV
df_dummies.to_csv(arq, index=False)

print(f'A base de dados transformada foi salva em: {arq}')

A base de dados transformada foi salva em: /Users/Administrador/Meu Drive/Estudo/CursoEBAC/2_Materiais/demo01_transformado.csv